config/routes.rb
Rails.application.routes.draw do
  # General Application Routes
  root to: 'sessions#new', as: 'sign_in'

  get 'index', to: 'dashboard#index', as: 'index'

  post 'dashboard/sign_in' 

  get 'new', to: 'registration#new', as: 'registration_page'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "register" => "user_accounts#new", :as => "register"

  resources :user_accounts
  resources :sessions

  # Main Application Routes for Drinks
  get 'prepare_drink', to: 'drink_management#prepare_drink', as: 'prepare_drink'
  post 'create_drink', to: 'drink_management#create_drink', as: 'create_drink'

  post 'add_ingredient', to: 'drink_management#add_ingredient', as: 'add_ingredient'
  post 'save_changes', to: 'drink_management#save_changes', as: 'save_changes'
  get 'edit_ingredients/:drink_id', to: 'drink_management#edit_ingredients', as: 'edit_ingredients' 
  post 'update_description', to: 'drink_management#update_description', as: 'update_description'
  get 'remove_ingredient/:drink_id/:ingredient_id', to: 'drink_management#remove_ingredient', as: 'remove_ingredient'
  post 'upload_file', to: 'drink_management#upload_file', as: 'upload_file'
  
  get 'drink_page/:drink_id', to: 'drink_management#drink_page', as: 'drink_page'
  post 'add_comment', to: 'drink_management#add_comment', as: 'add_comment'

  post 'like', to: 'drink_management#like', as: 'like'
  post 'unlike', to: 'drink_management#unlike', as: 'unlike'

  # Main Application Routes for User Account Page
  get 'account_page/:user_account_id', to: 'user_accounts#account_page', as: 'account_page'
  post 'reset_password', to: 'user_accounts#reset_password', as: 'reset_password'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def index
		@list_of_drinks = Drink.all
	end

end

app/views/dashboard/index.html.erb
<div id='pins' class='transitions-enabled'>
	<% @list_of_drinks.each do |i| %>
		<% if ( (current_user.id == i.user_account_id) && i.visibility ) || !i.visibility %>	
			<div class="box panel panel-default">
				<div id="panel-show" class="panel-heading pin-image">
					<% if i.avatar.present? %>
						<%= image_tag i.avatar.url(:medium), :alt => "#{i.avatar.url}" %>
					<% else %>
						No Image...
					<% end %>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-md-12 text-center">
						<%= link_to "#{i.drink_name}", drink_page_path(i.id) %>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12 text-center">
						Comments: <%= UserCommentAssociation.where("drink_id = ?", i.id).count %>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12 text-center user">
						Likes: <%= UserLikeAssociation.where(drink: i).where(like: true).count %>
						</div>
					</div>
				</div>
				<div class="panel-footer text-right">
					Created by <%= UserAccount.find(i.user_account_id).user_name %> 
				</div>
			</div>
		<% end %>
	<% end %>
</div>