config/routes.rb
Rails.application.routes.draw do
  # General Application Routes
  root to: 'sessions#new', as: 'sign_in'

  get 'index', to: 'dashboard#index', as: 'index'

  post 'dashboard/sign_in' 

  get 'new', to: 'registration#new', as: 'registration_page'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "register" => "user_accounts#new", :as => "register"

  resources :user_accounts
  resources :sessions

  # Main Application Routes for Drinks
  get 'prepare_drink', to: 'drink_management#prepare_drink', as: 'prepare_drink'
  post 'create_drink', to: 'drink_management#create_drink', as: 'create_drink'

  post 'add_ingredient', to: 'drink_management#add_ingredient', as: 'add_ingredient'
  post 'save_changes', to: 'drink_management#save_changes', as: 'save_changes'
  get 'edit_ingredients/:drink_id', to: 'drink_management#edit_ingredients', as: 'edit_ingredients' 
  post 'update_description', to: 'drink_management#update_description', as: 'update_description'
  get 'remove_ingredient/:drink_id/:ingredient_id', to: 'drink_management#remove_ingredient', as: 'remove_ingredient'
  post 'upload_file', to: 'drink_management#upload_file', as: 'upload_file'
  
  get 'drink_page/:drink_id', to: 'drink_management#drink_page', as: 'drink_page'
  post 'add_comment', to: 'drink_management#add_comment', as: 'add_comment'

  post 'like', to: 'drink_management#like', as: 'like'
  post 'unlike', to: 'drink_management#unlike', as: 'unlike'

  # Main Application Routes for User Account Page
  get 'account_page/:user_account_id', to: 'user_accounts#account_page', as: 'account_page'
  post 'reset_password', to: 'user_accounts#reset_password', as: 'reset_password'

end

app/controllers/drink_management_controller.rb
class DrinkManagementController < ApplicationController
  def prepare_drink
  
  end

  def create_drink
    params[:user_account_id] = current_user.id
    new_drink = Drink.new(drink_params)
    if new_drink.save
      Rails.logger.info "Created new drink"
      redirect_to edit_ingredients_path(new_drink.id)
    else
      redirect_to index_path
    end
  end

  def add_ingredient
    new_association = DrinkAssociation.new(drink_id: params[:drink_id], ingredient_id: params[:ingredient][:ingredient_id], quantity: params[:quantity])  
    if new_association.save
      Rails.logger.info "Ingredient saved to associated drink!"
    else
      redirect_to edit_ingredients_path(params[:drink_id])
    end
    redirect_to edit_ingredients_path(params[:drink_id])
  end

  def remove_ingredient
    remove_save = DrinkAssociation.where("drink_id = ? and ingredient_id = ?", params[:drink_id], params[:ingredient_id])
    if remove_save.present?
      remove_save.first.destroy
    end
    redirect_to edit_ingredients_path(params[:drink_id])
  end

  def save_changes
    begin
      save_request = DrinkAssociation.find(params[:association_id])
      if save_request.present? 
        if !(save_request.quantity == params[:quantity])
          save_request.update_attributes(quantity: params[:quantity])
        end
        if !(save_request.step_id == params[:step][:step_id])
          save_request.update_attributes(step_id: params[:step][:step_id])
        end
      end
      redirect_to edit_ingredients_path(params[:drink_id])     
    rescue
      redirect_to edit_ingredients_path(params[:drink_id])
    end
  end

  def edit_ingredients
    @new_drink = Drink.find(params[:drink_id])
    @list_of_unassociated_drink = DrinkAssociation.where("drink_id = ? and step_id = ?", @new_drink.id, 0)
    @list_of_drink_ingredients = DrinkAssociation.where("drink_id = ?", @new_drink.id)
    @list_of_mixing_ingredients = []
    @list_of_adding_after_ingredients = []   
    @list_of_garnishing_ingredients =[]
    @list_of_coating_rim_ingredients = []
    @list_of_drink_ingredients.each do |i|
      if i.step_id == 1
        @list_of_mixing_ingredients.push i
      elsif i.step_id == 2
        @list_of_adding_after_ingredients.push i
      elsif i.step_id == 3
        @list_of_coating_rim_ingredients.push i        
      elsif i.step_id == 4
        @list_of_garnishing_ingredients.push i
      end  
    end
    @list_of_steps = Step.all    
  end

  def drink_page
    @data_file = DataStorage.where("drink_id = ? and user_account_id = ?", params[:drink_id], current_user.id).first
    @drink = Drink.find_by(id: params[:drink_id])
    @comments_for_drink = UserCommentAssociation.where("drink_id = ?", @drink.id)
    @list_of_drink_ingredients = DrinkAssociation.where("drink_id = ?", @drink.id)
    @list_of_mixing_ingredients = []
    @list_of_adding_after_ingredients = []   
    @list_of_garnishing_ingredients =[]
    @list_of_coating_rim_ingredients = []
    @list_of_drink_ingredients.each do |i|
      if i.step_id == 1
        @list_of_mixing_ingredients.push i
      elsif i.step_id == 2
        @list_of_adding_after_ingredients.push i
      elsif i.step_id == 3
        @list_of_coating_rim_ingredients.push i        
      elsif i.step_id == 4
        @list_of_garnishing_ingredients.push i
      end  
    end   
  end

  def add_comment
    Rails.logger.info "====== PARAMS:  #{params}"
    UserCommentAssociation.create(user_account_id: current_user.id, drink_id: params[:drink_id], comment: params[:comment])
    redirect_to drink_page_path(params[:drink_id])
  end
  
  def upload_file
    @drink = Drink.find_by(id: params[:drink_id]).update_attributes(avatar: params[:avatar])
    redirect_to :back
  end

  def update_description
    drink = Drink.find_by(id: params[:drink_id])
    if drink && (drink.user_account_id == current_user.id)
      drink.update_attributes(description: params[:description])
      redirect_to edit_ingredients_path(params[:drink_id])
    else
      redirect_to index_path
    end
  end

  def like
    like_drink(current_user.id, params[:drink_id])
    redirect_to drink_page_path(params[:drink_id])
  end

  def unlike
    unlike_drink(current_user.id, params[:drink_id])
    redirect_to drink_page_path(params[:drink_id])
  end

  private 

  def user_comment_association_params
    params.permit(:id, :drink_id, :user_account_id, :comment)
  end

  def drink_association_params
    params.permit(:id, :drink_id, :ingredient_id, :step_id, :quantity)
  end

  def drink_params
    params.permit(:id, :drink_name, :visibility, :user_account_id, :avatar)
  end

  def ingredient_params
    params.permit(:id, :ingredient_name)
  end

  def data_storage_params
    params.permit(:id, :path, :original_file_name, :user_acount_id, :drink_id)
  end
end

app/views/drink_management/_add_ingredients.html.erb
<%= form_tag add_ingredient_path do %>
 	<%= hidden_field_tag "drink_id", new_drink.id %>
 	<%= hidden_field_tag "edit_mode", true %>
 	<div>
		<%= collection_select :ingredient, :ingredient_id, Ingredient.all, :id, :name_and_measure, :prompt => true %>
    	<%= label_tag :quantity %>
    	<%= text_field_tag :quantity %>
    	<%= submit_tag("Add") %>
    </div>
<% end %>

app/views/drink_management/_edit_ingredients_row.html.erb
<% if ingredients.present? %>
	<table>
		<% ingredients.each do |i| %>
			<% ingredient = Ingredient.find(i.ingredient_id) %>
			<tr> 
				<%= form_tag save_changes_path do %>
					
					<%= hidden_field_tag "association_id", i.id %>
					<%= hidden_field_tag "drink_id", new_drink.id %>
					<td>
						<%= collection_select :step, :step_id, Step.all, :id, :step_description, :prompt => true, :selected => i.step_id %>
					</td>
					<td>
						<%= text_field_tag :quantity, "#{i.quantity}" %> <%= WeightType.find(ingredient.weight_type_id).measure_type %> of <%= ingredient.ingredient_name %> 
					</td>
					<td>
						<%= submit_tag("Save Changes") %>
					</td>
				<% end %>
				<td>
					<%= link_to "Remove", remove_ingredient_path(new_drink.id, i.ingredient_id) %>
				</td>
			</tr>
		<% end %>
	</table>
<% else %>
	<div> No Ingredients Present. </div>
<% end %>

app/views/drink_management/_update_description.html.erb
<%= form_tag update_description_path do %>
 	<%= hidden_field_tag "drink_id", new_drink.id %>
	<%= text_area_tag(:description, "#{new_drink.description}", size: '50x10') %>
	<div>
		<%= submit_tag("Update description") %>
	</div>
<% end %>

app/views/drink_management/drink_page.html.erb
<div class="container-fluid">
	<div class="col-md-4">
		<div class="row">
			<% if @drink.avatar.present? %>
				<%= image_tag @drink.avatar.url(:medium), :alt => "#{@drink.avatar.url}" %>
			<% else %>
				<%= image_tag "/assets/images/static_drink.jpg", :alt => "static_drink.jpg" %>
			<% end %>
		</div>
		<div class="row">
			<div>
				<% if current_user.id == @drink.user_account_id %>
					<%= link_to "Edit Drink", edit_ingredients_path(@drink.id) %> 
				<% end %>
			</div>
		</div>
		<div class="row">
			Place Holder for list of related drinks...
		</div>
	</div>
	<div class="col-md-8">
		<div class="row">
			<div class="col-md-7 col-centered vcenter">
			<h3><%= @drink.drink_name %> by <%= UserAccount.find(@drink.user_account_id).user_name %></h3>
			</div>
			<div class="col-md-1 col-centered vcenter">
				<% if get_liked_drink(current_user.id, @drink.id).present? && get_liked_drink(current_user.id, @drink.id).first.like %>
					<%= form_tag unlike_path do %>
						<%= hidden_field_tag 'drink_id', @drink.id %>
						<%= submit_tag "unlike" %>
					<% end %>
				<% elsif (get_liked_drink(current_user.id, @drink.id).present? && !get_liked_drink(current_user.id, @drink.id).first.like) || !get_liked_drink(current_user.id, @drink_id).present? %>
					<%= form_tag like_path do %>
						<%= hidden_field_tag 'drink_id', @drink.id %>
						<%= submit_tag "like" %>
					<% end %>
				<% end %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<%= @drink.description %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<ul>
					<li>
						<h4> Ingredients Mixing in with each other. </h4>
						<ul>
							<% if @list_of_mixing_ingredients.present? %>
								<% @list_of_mixing_ingredients.each do |i| %>
									<li> Mix <%= Ingredient.find(i.ingredient_id).ingredient_name %> in drink
									</li>
								<% end %>
							<% else %>
								<td> 
									No ingredient's present to be mixed in.
								</td> 
							<% end %>
						</ul>
					</li>	

					<li>
						<h4> Adding Ingredients after mixing. </h4>
						<ul>
							<% if @list_of_adding_after_ingredients.present? %>
								<% @list_of_adding_after_ingredients.each do |i| %>
										<li> Pour <%= Ingredient.find(i.ingredient_id).ingredient_name %> in
										</li>
								<% end %>
							<% else %> 	
								<li> 
									No ingredient's present to be Added in.
								</li> 
							<% end %>
						</ul>
					</li>

					<li>
						<h4> Garnish Ingredients after mixing. </h4>
						<ul>
							<% if @list_of_garnishing_ingredients.present? %>
								<% @list_of_garnishing_ingredients.each do |i| %>
										<li> Add <%= Ingredient.find(i.ingredient_id).ingredient_name %> as a garnish.
										</li>
								<% end %>
							<% else %> 	
								<li> 
									No ingredient's present to be Added in.
								</li> 
							<% end %>
						</ul>
					</li>

					<li>
						<h4> Coat Rim with the following Ingredients. </h4>
						<ul>
							<% if @list_of_coating_rim_ingredients.present? %>
								<% @list_of_coating_rim_ingredients.each do |i| %>
										<li> Coat <%= Ingredient.find(i.ingredient_id).ingredient_name %> on rim.
										</li>
								<% end %>
							<% else %> 	
								<li> 
									No ingredient's present to be Added in.
								</li> 
							<% end %>
						</ul>
					</li>
				</ul>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<div class="detailBox">
				    <div class="titleBox">
				      <label>Comment</label>
				    </div>

					<div>
				  		<div class="form-group">
							<%= form_tag add_comment_path do %>
								<%= hidden_field_tag :drink_id, @drink.id %>
								<%= text_area_tag(:comment, "", placeholder: "Add comment...", size: '50x10') %>
							<div>
								<%= submit_tag("Comment", :class => "btn btn-default") %>
							</div>
							<% end %>
						</div>
					</div>
					<div>
						<div class="actionBox">
				        	<ul class="commentList">
								<% @comments_for_drink.each do |comment| %>
									<li>
										<div class="commentText">
											<p class=""><%= comment.comment %></p> <span class="date sub-text"><%= UserAccount.find_by(id: comment.user_account_id).user_name %> @ <%= comment.created_at %></span>	
										</div>
									</li>
								<% end %>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/drink_management/edit_ingredients.html.erb
<div class="row">
	<div class="col-md-4">
		<% if @new_drink.avatar.present? %>
			<%= image_tag @new_drink.avatar.url(:medium), :alt => "#{@new_drink.avatar.url}" %>
		<% else %>
			<%= image_tag "/assets/images/static_drink.jpg", :alt => "static_drink.jpg" %>
		<% end %>
		<div class="row">	
			<% if current_user.id == @new_drink.user_account_id %>
				<%= form_tag upload_file_path, :multipart => true do %>
				    <%= hidden_field_tag "drink_id", @new_drink.id %>
					<%= file_field_tag :avatar %>
					<%= submit_tag("Upload") %>
				<% end %>
			<% end %>
		</div>
		<div class="row">
			<%= link_to "Done Editing", drink_page_path(@new_drink.id) %>
		</div>
	</div>

	<div class="col-md-8">
		<div class="row">
			<h3> Editing Ingredients for <%= @new_drink.drink_name %></h3>
		</div>
		<div class="row">
			<%= render partial: 'update_description', locals: {new_drink: @new_drink} %>
		</div>
		<div class="row">
			<ul>
				<li>
					<h3> Add Ingredient Interace </h3>
					<%= render partial: 'add_ingredients', locals: {new_drink: @new_drink} %>
				</li>
				<li>
					<h3> Unassociated Ingredient with step </h3>
					<%= render partial: 'edit_ingredients_row', locals: {ingredients: @list_of_unassociated_drink, new_drink: @new_drink} %>		 
				</li>
				<li>
					<h3> Ingredients Mixing in with each other. </h3>
					<%= render partial: 'edit_ingredients_row', locals: {ingredients: @list_of_mixing_ingredients, new_drink: @new_drink} %>
				</li>	

				<li>
					<h3> Adding Ingredients after mixing. </h3>
					<%= render partial: 'edit_ingredients_row', locals: {ingredients: @list_of_adding_after_ingredients, new_drink: @new_drink} %>
				</li>

				<li>
					<h3> Garnish Ingredients after mixing. </h3>
					<%= render partial: 'edit_ingredients_row', locals: {ingredients: @list_of_garnishing_ingredients, new_drink: @new_drink} %>
				</li>

				<li>
					<h3> Coat Rim with the following Ingredients. </h3>
					<%= render partial: 'edit_ingredients_row', locals: {ingredients: @list_of_coating_rim_ingredients, new_drink: @new_drink} %>
				</li>
			</ul>
		</div>
	</div>
</div>

app/views/drink_management/prepare_drink.html.erb
<h1> Drink Creation </h1>

<%= form_tag create_drink_path do %>
        <div>
            <%= label_tag :drink_name %>
            <%= text_field_tag :drink_name %>
        </div>
        <div>
			<%= radio_button_tag(:visibility, "true") %>
			<%= label_tag(:visibility_true, "I want my drink to be Private.") %>
		</div>
		<div>
			<%= radio_button_tag(:visibility, "false") %>
			<%= label_tag(:visibility_false, "I want to share this drink.") %>
        </div>

        <%= submit_tag("Proceed to Creation!") %>

<% end %>