config/routes.rb
Rails.application.routes.draw do
  # General Application Routes
  root to: 'sessions#new', as: 'sign_in'

  get 'index', to: 'dashboard#index', as: 'index'

  post 'dashboard/sign_in' 

  get 'new', to: 'registration#new', as: 'registration_page'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "register" => "user_accounts#new", :as => "register"

  resources :user_accounts
  resources :sessions

  # Main Application Routes for Drinks
  get 'prepare_drink', to: 'drink_management#prepare_drink', as: 'prepare_drink'
  post 'create_drink', to: 'drink_management#create_drink', as: 'create_drink'

  post 'add_ingredient', to: 'drink_management#add_ingredient', as: 'add_ingredient'
  post 'save_changes', to: 'drink_management#save_changes', as: 'save_changes'
  get 'edit_ingredients/:drink_id', to: 'drink_management#edit_ingredients', as: 'edit_ingredients' 
  post 'update_description', to: 'drink_management#update_description', as: 'update_description'
  get 'remove_ingredient/:drink_id/:ingredient_id', to: 'drink_management#remove_ingredient', as: 'remove_ingredient'
  post 'upload_file', to: 'drink_management#upload_file', as: 'upload_file'
  
  get 'drink_page/:drink_id', to: 'drink_management#drink_page', as: 'drink_page'
  post 'add_comment', to: 'drink_management#add_comment', as: 'add_comment'

  post 'like', to: 'drink_management#like', as: 'like'
  post 'unlike', to: 'drink_management#unlike', as: 'unlike'

  # Main Application Routes for User Account Page
  get 'account_page/:user_account_id', to: 'user_accounts#account_page', as: 'account_page'
  post 'reset_password', to: 'user_accounts#reset_password', as: 'reset_password'

end

app/models/user_account.rb
class UserAccount < ActiveRecord::Base
  has_many :user_comment_association
  has_many :comments, :through => :user_comment_association
  has_many :drinks, :through => :user_comment_association

  has_many :user_like_association
  has_many :drinks, :through => :user_comment_association
  has_many :likes, :through => :user_comment_association  

  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :user_name
  validates_uniqueness_of :user_name
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(user_name, password)
    user = find_by_user_name(user_name)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/user_accounts_controller.rb
class UserAccountsController < ApplicationController

  def new
    @user = UserAccount.new
  end

  def create
    @user = UserAccount.new(user_accounts_params)
    if @user.save
      redirect_to index_path, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def account_page
    #@list_of_created_drinks = 
    #@list_of_personal_favorites = 
  end

  def reset_password
    if current_user.password_hash == BCrypt::Engine.hash_secret(params[:current_password], current_user.password_salt)
      if params[:new_password] == params[:password_confirm]
        password_hash = BCrypt::Engine.hash_secret(params[:new_password], current_user.password_salt)
        current_user.update_attributes(password_hash: password_hash)
        redirect_to account_page_path(current_user.id)
      else
        redirect_to account_page_path(current_user.id)
      end
    else
      redirect_to account_page_path(current_user.id)
    end
  end

  private

  def user_accounts_params
    params.require(:user_account).permit(:first_name, :last_name, :email, :user_name, :password)
  end

end

app/views/user_accounts/account_page.html.erb
<h3> Reset Password </h3>
<%= form_tag reset_password_path do %>
    <%= label_tag :current_password %>
    <%= password_field_tag :current_password %>
    <%= label_tag :new_password %>
    <%= password_field_tag :new_password %>
    <%= label_tag :password_confirm %>
    <%= password_field_tag :password_confirm %>
    <%= submit_tag "Change Password" %>
<% end %>

app/views/user_accounts/new.html.erb
<h1>Registration</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>  
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>