config/routes.rb
Rails.application.routes.draw do
  # General Application Routes
  root to: 'sessions#new', as: 'sign_in'

  get 'index', to: 'dashboard#index', as: 'index'

  post 'dashboard/sign_in' 

  get 'new', to: 'registration#new', as: 'registration_page'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "register" => "user_accounts#new", :as => "register"

  resources :user_accounts
  resources :sessions

  # Main Application Routes for Drinks
  get 'prepare_drink', to: 'drink_management#prepare_drink', as: 'prepare_drink'
  post 'create_drink', to: 'drink_management#create_drink', as: 'create_drink'

  post 'add_ingredient', to: 'drink_management#add_ingredient', as: 'add_ingredient'
  post 'save_changes', to: 'drink_management#save_changes', as: 'save_changes'
  get 'edit_ingredients/:drink_id', to: 'drink_management#edit_ingredients', as: 'edit_ingredients' 
  post 'update_description', to: 'drink_management#update_description', as: 'update_description'
  get 'remove_ingredient/:drink_id/:ingredient_id', to: 'drink_management#remove_ingredient', as: 'remove_ingredient'
  post 'upload_file', to: 'drink_management#upload_file', as: 'upload_file'
  
  get 'drink_page/:drink_id', to: 'drink_management#drink_page', as: 'drink_page'
  post 'add_comment', to: 'drink_management#add_comment', as: 'add_comment'

  post 'like', to: 'drink_management#like', as: 'like'
  post 'unlike', to: 'drink_management#unlike', as: 'unlike'

  # Main Application Routes for User Account Page
  get 'account_page/:user_account_id', to: 'user_accounts#account_page', as: 'account_page'
  post 'reset_password', to: 'user_accounts#reset_password', as: 'reset_password'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bartini</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href=<%= current_user ? index_path : sign_in_path %>>Bartini</a>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	  	<!-- Collect the nav links, forms, and other content for toggling -->
			<ul class="nav navbar-nav">
		  	<% if current_user %>
				<li><%= link_to "Account", account_page_path(current_user.id) %><span class="sr-only">(current)</span></a></li>
				<li><%= link_to 'Create Drink', prepare_drink_path %></li>
		      	<form class="navbar-form navbar-left" role="search">
			        <div class="form-group">
			          <input type="text" class="form-control" placeholder="Search">
			        </div>
			        <button type="submit" class="btn btn-default">Submit</button>
		      	</form>
		      	<ul class="nav navbar-nav pull-right">
					<li>Welcome <%= current_user.user_name %>!</li>
					<li><%= link_to "Log out", log_out_path %></li>
				</ul>
		  	<% else %>
		  		<li class="active"><%= link_to "log in", log_in_path %><span class="sr-only">(current)</span></a></li>
			    <li><%= link_to "Register", register_path %></li>
	  		<% end %>
	  		</ul>
  		</div>
	</div>
	<div class="container">	
		<div class="jumbotron">
			<%= yield %>
		</div>
	</div>

</body>
</html>